require 'const/vfs_const'

# Constants related with ACL
module Acl
  # include Vfs
  # node acl
  ACL_NODE_NO_ACCESS = 0
  ACL_NODE_READ = 1
  ACL_NODE_WRITE = 2
  ACL_NODE_DELETE = 4
  ACL_NODE_CONTROL = 8
  ACL_NODE_STICKY = 16

  # vfs acl
  ACL_VFS_NO_ACCESS = 0
  ACL_VFS_READ = 1
  ACL_VFS_WRITE = 2
  ACL_VFS_DELETE = 4
  ACL_VFS_CONTROL = 8
  ACL_VFS_STICKY = 16
  ACL_VFS_WORM = (ACL_VFS_READ | ACL_VFS_WRITE | ACL_VFS_STICKY)

  ACL_NOTIFY_NONE = 0
  ACL_NOTIFY_IMMEDIATE = 1
  ACL_NOTIFY_DELAYED = 2
  ACL_NOTIFY_DEFAULT = ACL_NOTIFY_IMMEDIATE

  ACL_NODE_SUPERUSER_ACCESS = ( ACL_NODE_READ | ACL_NODE_WRITE | ACL_NODE_DELETE | ACL_NODE_CONTROL )
  ACL_NODE_FULL_ACCESS = ( ACL_NODE_READ | ACL_NODE_WRITE | ACL_NODE_DELETE | ACL_NODE_CONTROL )
  ACL_NODE_RWD_ACCESS = ( ACL_NODE_READ | ACL_NODE_WRITE | ACL_NODE_DELETE )

  ACL_SUPER_USER_NAME = 'root'
  ACL_SUPER_USER_INITIAL_APASSWORD = '@All4OneOne4All'
  ACL_SUPER_USER_DISPLAY_NAME = 'スーパーユーザー'

  # ACLs set
  ACLS_SYSTEM_AREA4_SUPERUSER = { user: ACL_NODE_SUPERUSER_ACCESS, group: ACL_NODE_RWD_ACCESS,
                                  world: ACL_NODE_NO_ACCESS }
  ACLS_SYSTEM_AREA4_WHEEL = { user: ACL_NODE_FULL_ACCESS, group: ACL_NODE_FULL_ACCESS, world: ACL_NODE_NO_ACCESS }
  ACLS_SYSTEM_AREA4_WORLD = { user: ACL_NODE_NO_ACCESS, group: ACL_NODE_NO_ACCESS, world: ACL_NODE_NO_ACCESS }
  ACLS_USER_AREA = { user: ACL_NODE_RWD_ACCESS, group: ACL_NODE_RWD_ACCESS, world: ACL_NODE_NO_ACCESS }
  ACLS_PUBLIC_AREA = { user: ACL_NODE_FULL_ACCESS, group: ACL_NODE_RWD_ACCESS, world: ACL_NODE_READ }
  ACLS_SHARED_AREA = { user: ACL_NODE_FULL_ACCESS, group: ACL_NODE_RWD_ACCESS, world: ACL_NODE_NO_ACCESS }

  # for test
  ADMIN_SESSION_ID_SEED = '_special_administrator_session'
  ADMIN_SESSION_ID = 'cd20fddc9b4613bf671eb8d42e0274919badb553'

  # initial session : for login session
  INITIAL_SESSION_ID_SEED = '_initial_session_'
  INITIAL_SESSION_ID = '4d706346dd8891af503c47f288932b470c659757'

  # gid for world
  ACL_WORLD_GID = -1

  # uid, gid for SUPERUSER
  ACL_SUPERUSER_UID = 0
  ACL_SUPERUSER_GID = 0

  # user level
  ACL_SUPER_USER_LEVEL_X = -1
  ACL_SUPER_USER_LEVEL_Y = -1

  # not set
  ACL_NO_VALUE = -1

  # default acl values
  ACL_DEFAULT_UID_ACCESS_RIGHT = ( ACL_NODE_READ | ACL_NODE_WRITE | ACL_NODE_DELETE | ACL_NODE_CONTROL )
  ACL_DEFAULT_GID_ACCESS_RIGHT = ( ACL_NODE_READ | ACL_NODE_WRITE | ACL_NODE_DELETE )
  ACL_DEFAULT_WORLD_ACCESS_RIGHT = ACL_NODE_NO_ACCESS

  # prefix string
  ACL_PREFIX = 'spin_acl'
end
